<a href="https://colab.research.google.com/github/IsagiYoichi640/Data-Science/blob/main/Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
from numpy import random

In [64]:
num1=np.array(random.randint(1,20,size=20))
print(num1)

[ 1 17 18 14  9  5  7 15  9  3  5 15  5  3  8  7 18  7 11 10]


In [70]:
#sort in ascending order
print(np.sort(num1))

[ 1  3  3  5  5  5  7  7  7  8  9  9 10 11 14 15 15 17 18 18]


In [71]:
#sort in descending order
print(np.sort(num1)[::-1])

[18 18 17 15 15 14 11 10  9  9  8  7  7  7  5  5  5  3  3  1]
